#Tentukan Role | sudoer > role user (bos)
sudo : required

# OS yang mau dipake
# OS -> precies, trusty, xenial
dist : trusty

#bahasa yang digunakan
language : php

#versi bahasa yang digunakan
php :
  - 7.1

#tentukan branch
branches :
  only:
    - master # -> QA/Staging
    - develop # -> DevServer

# Before Install
before_install:
  - wget https://phar.phpunit.de/phpunit-6.5.phar
  - chmod +x phpunit-6.5.phar
  - sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
  - phpunit --version
# Install
install:
# Before script -> sebelum melakukan main execution
before_script:
# script -> main excution
script: